theme: jekyll-theme-cayman
title: Open Science Lenia
description: Open Science and Open Source projects for the Continuous Cellular Automata
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
